import type {
  MallAddress,
  MallCategory,
  MallCoupon,
  MallGoods,
  MallOrder,
  MallUserProfile,
} from "../../types/mall";

export const mallCategoryList: MallCategory[] = [
  { id: 1, name: "应季鲜果", icon: "🍊" },
  { id: 2, name: "轻食乳品", icon: "🥛" },
  { id: 3, name: "休闲零食", icon: "🍪" },
  { id: 4, name: "精选礼盒", icon: "🎁" },
];

export const mallGoodsList: MallGoods[] = [
  {
    id: 1001,
    categoryId: 1,
    categoryName: "应季鲜果",
    name: "云南高山蓝莓 125g",
    characteristic: "当日冷链到仓，酸甜平衡，适合早餐酸奶碗",
    price: 19.9,
    originalPrice: 24.9,
    unit: "盒",
    stock: 168,
    monthlySales: 392,
    tags: ["爆款", "冷链"],
    bannerList: ["🫐", "🥣", "🚚"],
    detailList: ["晨采蓝莓", "颗粒饱满", "坏果包赔"],
    defaultVariantId: 20001,
    variants: [
      {
        id: 20001,
        specs: {},
        specNames: ["规格"],
        price: 19.9,
        originalPrice: 24.9,
        unit: "盒",
        stock: 168,
      },
    ],
  },
  {
    id: 1002,
    categoryId: 1,
    categoryName: "应季鲜果",
    name: "赣南脐橙 优选装 5kg",
    characteristic: "果汁丰富，甜度稳定，适合家庭囤货",
    price: 49.9,
    originalPrice: 59.9,
    unit: "箱",
    stock: 96,
    monthlySales: 248,
    tags: ["家庭装", "产地直发"],
    bannerList: ["🍊", "📦", "🌿"],
    detailList: ["果园直采", "净重足量", "坏果补发"],
    defaultVariantId: 20002,
    variants: [
      {
        id: 20002,
        specs: {},
        specNames: ["规格"],
        price: 49.9,
        originalPrice: 59.9,
        unit: "箱",
        stock: 96,
      },
    ],
  },
  {
    id: 1003,
    categoryId: 2,
    categoryName: "轻食乳品",
    name: "A2 高钙纯牛奶 250ml*10",
    characteristic: "早餐常备，口感醇厚，适合全家饮用",
    price: 36.8,
    originalPrice: 42.8,
    unit: "提",
    stock: 125,
    monthlySales: 185,
    tags: ["高钙", "早餐"],
    bannerList: ["🥛", "🌞", "💪"],
    detailList: ["配料简单", "奶香浓郁", "日期新鲜"],
    defaultVariantId: 20003,
    variants: [
      {
        id: 20003,
        specs: {},
        specNames: ["规格"],
        price: 36.8,
        originalPrice: 42.8,
        unit: "提",
        stock: 125,
      },
    ],
  },
  {
    id: 1004,
    categoryId: 3,
    categoryName: "休闲零食",
    name: "轻烘焙海盐开心果 500g",
    characteristic: "颗粒完整，低温烘焙，追剧分享都很合适",
    price: 58,
    originalPrice: 69,
    unit: "袋",
    stock: 76,
    monthlySales: 133,
    tags: ["办公室", "追剧零食"],
    bannerList: ["🥜", "🎬", "🧂"],
    detailList: ["低温轻烘焙", "开口率高", "罐装封鲜"],
    defaultVariantId: 20004,
    variants: [
      {
        id: 20004,
        specs: {},
        specNames: ["规格"],
        price: 58,
        originalPrice: 69,
        unit: "袋",
        stock: 76,
      },
    ],
  },
  {
    id: 1005,
    categoryId: 4,
    categoryName: "精选礼盒",
    name: "城市下午茶礼盒",
    characteristic: "曲奇、挂耳咖啡、果茶组合，送礼不出错",
    price: 89,
    originalPrice: 109,
    unit: "盒",
    stock: 58,
    monthlySales: 88,
    tags: ["送礼", "礼盒"],
    bannerList: ["🎁", "☕", "🍪"],
    detailList: ["商务送礼", "节日关怀", "独立包装"],
    defaultVariantId: 20005,
    variants: [
      {
        id: 20005,
        specs: {},
        specNames: ["规格"],
        price: 89,
        originalPrice: 109,
        unit: "盒",
        stock: 58,
      },
    ],
  },
  {
    id: 1006,
    categoryId: 3,
    categoryName: "休闲零食",
    name: "空气烘焙紫薯脆片 200g",
    characteristic: "非油炸工艺，入口酥脆，控制负担更轻松",
    price: 22.8,
    originalPrice: 29.8,
    unit: "袋",
    stock: 210,
    monthlySales: 301,
    tags: ["非油炸", "轻负担"],
    bannerList: ["🍠", "💜", "✨"],
    detailList: ["配料干净", "轻盐少糖", "办公室补给"],
    defaultVariantId: 20006,
    variants: [
      {
        id: 20006,
        specs: {},
        specNames: ["规格"],
        price: 22.8,
        originalPrice: 29.8,
        unit: "袋",
        stock: 210,
      },
    ],
  },
];

export const mallAddressList: MallAddress[] = [
  {
    id: 1,
    name: "陈晓雯",
    mobile: "13800138000",
    province: "浙江省",
    city: "杭州市",
    district: "滨江区",
    detail: "江虹路创智天地 2 幢 1203 室",
    isDefault: true,
  },
  {
    id: 2,
    name: "张一鸣",
    mobile: "13900139000",
    province: "上海市",
    city: "上海市",
    district: "闵行区",
    detail: "申长路 799 号虹桥天地 3 号楼",
    isDefault: false,
  },
];

export const mallCouponList: MallCoupon[] = [
  {
    id: 1,
    name: "新人立减券",
    amount: 10,
    minAmount: 59,
    expireTime: "2026-03-31 23:59",
    status: "unused",
  },
  {
    id: 2,
    name: "鲜果专区券",
    amount: 15,
    minAmount: 99,
    expireTime: "2026-03-20 23:59",
    status: "unused",
  },
  {
    id: 3,
    name: "会员回馈券",
    amount: 20,
    minAmount: 129,
    expireTime: "2026-02-28 23:59",
    status: "expired",
  },
];

export const mallUserProfile: MallUserProfile = {
  id: 20260309,
  nickName: "陈晓雯",
  mobile: "13800138000",
  levelName: "银卡会员",
  points: 1260,
  couponCount: 2,
};

export const mallOrderList: MallOrder[] = [
  {
    id: "MO20260308001",
    status: "shipping",
    createTime: "2026-03-08 18:40",
    totalAmount: 86.7,
    payAmount: 76.7,
    addressText: "陈晓雯 13800138000 浙江省杭州市滨江区江虹路创智天地 2 幢 1203 室",
    itemList: [
      { id: 300001, goodsId: 1001, name: "云南高山蓝莓 125g", price: 19.9, quantity: 2 },
      { id: 300002, goodsId: 1006, name: "空气烘焙紫薯脆片 200g", price: 22.8, quantity: 2 },
    ],
  },
  {
    id: "MO20260307012",
    status: "finished",
    createTime: "2026-03-07 12:18",
    totalAmount: 49.9,
    payAmount: 49.9,
    addressText: "张一鸣 13900139000 上海市上海市闵行区申长路 799 号虹桥天地 3 号楼",
    itemList: [{ id: 300003, goodsId: 1002, name: "赣南脐橙 优选装 5kg", price: 49.9, quantity: 1 }],
  },
];
